---
- hosts: all
  user: jaoua
  gather_facts: no
  roles:
  - kwoodson.yedit
  tasks:
  - name: get a specific value
    yedit:
      src: /home/jaoua/logstash.yml
      state: list
      key: xpack.management.elasticsearch.username
    register: yeditout
  - debug: var=yeditout