---
- hosts: all
  user: jaoua
  gather_facts: no
  roles:
  - kwoodson.yedit
  tasks:
  - name: get a specific value
    yedit:
      src: /home/jaoua/logstash.yml
      edits:
      - key: xpack.management.elasticsearch.username
        value: a
      - key: a.b.c.d
        value: xpack.management.elasticsearch.password
      state: present
    register: yeditout
  - debug: var=yeditout