---
- hosts: localhost
  gather_facts: no
  roles:
  - kwoodson.yedit
  tasks:
  - name: get a specific value
    yedit:
      src: /etc/logstash/logstash.yaml
      state: list
      key: xpack.management.pipeline.id
    register: yeditout
  - debug: var=yeditout