---
- hosts: all
  user: jaoua
  gather_facts: no
  roles:
  - kwoodson.yedit
  tasks:
  - name: get a specific value
    yedit:
      src: /etc/logstash/pipelines.yml
      separator: ':'
      state: list
    register: yeditout
  - debug: var=yeditout