---
- hosts: all
  user: jaoua
  become: yes
  become_user: jaoua
  become_method: sudo
  gather_facts: no 
  roles:
  - kwoodson.yedit
  tasks:
  - name: remove a specific value
    yedit:
      src: /etc/logstash/pipelines.yml
      separator: ':'
      update: true
      key: "[{{ pipeline_index }}]['pipeline.id']"
      state: absent
    register: yeditout
  - debug: var=yeditout