---
- hosts: all
  user: jaoua
  gather_facts: no 
  roles:
  - kwoodson.yedit
  tasks:
  - name: remove a specific value
    yedit:
      src: /etc/logstash/logstash.yml
      separator: ':'
      append: true
      key: xpack.management.pipeline.id
      value: "{{ pipeline_id }}"
      state: absent
    register: yeditout
  - debug: var=yeditout