---
- hosts: all
  user: jaoua
  become: yes
  become_user: jaoua
  become_method: sudo
  gather_facts: no 
  roles:
  - kwoodson.yedit
  tasks:
  - name: get a specific value
    yedit:
      src: /etc/logstash/pipelines.yml
      separator: ':'
      key: "[{{ pipeline_index }}]"
      state: list
    register: tobedel
  - name: remove a specific value
    yedit:
      src: /etc/logstash/pipelines.yml
      separator: ':'
      update: true
      value: tobedel.result
      state: absent
    register: yeditout
  - debug: var=yeditout