---
- hosts: all
  user: jaoua
  become: yes
  become_user: jaoua
  become_method: sudo
  gather_facts: no
  roles:
  - kwoodson.yedit
  tasks:
  - name: add a specific value
    yedit:
      src: /etc/logstash/pipelines.yml
      separator: ':'
      update: true
      index: "{{ pipeline_index }}"
      value: 
        pipeline.id: "{{ pipeline_id }}"
        config.string: "{{ pipeline_string }}"
      state: present
    register: yeditout
  - debug: var=yeditout